[[cells]]
name = "pact_escrow_lock"
enable_type_id = true

  [cells.location]
  file = "/Users/oluwaseun/Desktop/pactagent/contracts/build/release/pact_escrow_lock"

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0xf543e3e574a28c6ca780d5739803d1a54ffeee67"
hash_type = "type"
