export enum AgreementStatus {
  DRAFT = 'DRAFT',
  CANCELLED = 'CANCELLED',
  FUNDED = 'FUNDED',
  PROOF_SUBMITTED = 'PROOF_SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
  ACTIVE = 'ACTIVE',
  PROOF_SUBMITTED = 'PROOF_SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
}

export enum ProofType {
  URL = 'URL',
  TEXT = 'TEXT',
  FILE_HASH = 'FILE_HASH',
}

export enum ReleaseMode {
  FULL = 'FULL',
  PARTIAL = 'PARTIAL',
}

export enum ReviewerMode {
  AUTO = 'AUTO',
  HYBRID = 'HYBRID',
  MANUAL = 'MANUAL',
}

export enum PayoutNetwork {
  CKB = 'CKB',
  FIBER = 'FIBER',
}

export enum EscrowModel {
  TREASURY_BRIDGE = 'TREASURY_BRIDGE',
  ONCHAIN_LOCK = 'ONCHAIN_LOCK',
}

export enum PricingMode {
  FIXED_CKB = 'FIXED_CKB',
  USD_EQUIVALENT = 'USD_EQUIVALENT',
}

export enum ReserveHealthStatus {
  HEALTHY = 'HEALTHY',
  TOP_UP_REQUIRED = 'TOP_UP_REQUIRED',
}

export enum SettlementStatus {
  UNFUNDED = 'UNFUNDED',
  FUNDING_PENDING = 'FUNDING_PENDING',
  FUNDED = 'FUNDED',
  PAYOUT_PENDING = 'PAYOUT_PENDING',
  PAYOUT_CONFIRMED = 'PAYOUT_CONFIRMED',
  SPLIT_PENDING = 'SPLIT_PENDING',
  SPLIT_CONFIRMED = 'SPLIT_CONFIRMED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUND_CONFIRMED = 'REFUND_CONFIRMED',
  DISPUTE_LOCKED = 'DISPUTE_LOCKED',
  FAILED = 'FAILED',
}

export enum SettlementDirection {
  FUNDING = 'FUNDING',
  PAYOUT = 'PAYOUT',
  REFUND = 'REFUND',
}

export enum SettlementRecordStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
}

export enum LogLevel {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
}

export enum AgentEventType {
  AGREEMENT_CREATED = 'AGREEMENT_CREATED',
  MILESTONE_ACTIVATED = 'MILESTONE_ACTIVATED',
  FUNDING_PENDING = 'FUNDING_PENDING',
  FUNDING_CONFIRMED = 'FUNDING_CONFIRMED',
  PROOF_SUBMITTED = 'PROOF_SUBMITTED',
  RULE_CHECK_STARTED = 'RULE_CHECK_STARTED',
  RULE_CHECK_PASSED = 'RULE_CHECK_PASSED',
  RULE_CHECK_FAILED = 'RULE_CHECK_FAILED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  AI_RECOMMENDATION_READY = 'AI_RECOMMENDATION_READY',
  RELEASE_PREPARED = 'RELEASE_PREPARED',
  RELEASE_SENT = 'RELEASE_SENT',
  SETTLEMENT_CONFIRMED = 'SETTLEMENT_CONFIRMED',
  REFUND_SENT = 'REFUND_SENT',
  FIBER_PAYOUT_INITIATED = 'FIBER_PAYOUT_INITIATED',
  FIBER_PAYOUT_CONFIRMED = 'FIBER_PAYOUT_CONFIRMED',
  ERROR = 'ERROR',
}

export enum DisputeRecommendation {
  APPROVE_PAYOUT = 'APPROVE_PAYOUT',
  REFUND_CLIENT = 'REFUND_CLIENT',
  REQUEST_MORE_EVIDENCE = 'REQUEST_MORE_EVIDENCE',
  ESCALATE_MANUAL_REVIEW = 'ESCALATE_MANUAL_REVIEW',
}
